version: "3"

services:
  mqtt-broker:
    image: eclipse-mosquitto
    networks:
      - mqtt-network
    ports:
      - 1883:1883

  database:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: PF2020
    volumes:
      - ./db:/data/db
    networks:
      - db-network
    ports:
      - 27017:27017

  webclient:
    build: ./plantfactoryweb
    networks:
      - mqtt-network
    ports:
      - 8080:8080
    depends_on:
      - node-red

  node-red:
    build: ./plantfactorynodered
    environment:
      - TZ=Europe/Budapest
    ports:
      - "1881:1880"
    networks:
      - mqtt-network
      - db-network
    volumes:
      - ./plantfactorynodered:/data
    links:
      - "mqtt-broker:broker"
    depends_on:
      - mqtt-broker
      - database

networks:
  mqtt-network:
  db-network:
